### ISSUE TITLE
Update Jitsi-based dependencies to latest release.

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/ofmeet-openfire-plugin#15]
The Jitsi-based dependencies should be updated to their last versions, so that the latest upstream changes are pulled in.

This will, among others, pull in the new 'vertical' film strip (for which we'll need some configurable settings).

**Comment by guusdk** [comment]
Latest release at the time of writing:

- Jitsi Meet: 1.0.2100
- Jitsi Jicofo: 1.0-20170707.231635-3
- Jitsi Videobridge Openfire plugin: which is based on JVB 1.0-20170710.163722-371

**Comment by deleolajide** [comment]
>Jitsi Videobridge Openfire plugin: which is based on JVB 1.0-20170710.163722-371

That would be 2.1-20170711.144128-2

Just built and tested ok with this.

**Comment by guusdk** [comment]
Pressed enter to soon, it appears. I've updated the original comment. 

Thanks for testing. I've got a couple of these issues based on your bigger one lined up. I'll push soon

**Comment by guusdk** [comment]
I've updated Jitsi-meet to 1.0.2181 to pull in the upstream changed needed for #22
