### ISSUE TITLE
Support new startAudioOnly and startScreenSharing parameters

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/ofmeet-openfire-plugin#22]
In the old version 0.3.x, we have URL parameters novideo and noaudio that were used to start a conference in audio only or video only modes. JitsiMeet now supports two new config parameters startAudioOnly and startScreenSharing which can roughly do the same and more.

We need to add this ability to the current version. In my fork, I do the following:

````
    if (urlParam("audio_only")) config.startAudioOnly = true;   
    if (urlParam("screen_share")) config.startScreenSharing = true;
````

**Comment by guusdk** [comment]
I don't think we need custom code for this anymore. Jitsi Meet has something pretty similar itself now. I'm working on updating the source, so that we can try it out.

**Comment by deleolajide** [comment]
>I don't think we need custom code for this anymore
I think we do. The requirement is to allow audio only and screen share only to be initiated from the URL on demand. Quite different from an application wide setting in config.js as implemented by Jitsi Meet. I have applications that depend on this to start an audio-conference instead of a video-conference by the URL

**Comment by guusdk** [comment]
I'm not sure about the screen-share option, but the audio-only mode, as well as 'startWithAudioMuted' and 'startWithVideoMuted' settings can be defined in the config.js (as you describe), but, that configuration can now be overridden by supplying a parameter on the URL. Try, for example: https://beta.meet.jit.si/testroom#config.startWithVideoMuted=true

Isn't that what you're after? If so, then we'd only have to apply a similar fix for screen-share (which might be accepted upstream, too).

**Comment by deleolajide** [comment]
Yes. The key feature was being able to override config from the url. Really B-)

**Comment by deleolajide** [comment]
https://beta.meet.jit.si/testroom#config.startScreenSharing=true

also works

**Comment by guusdk** [comment]
I've added some admin console configuration for configuring ofmeet to start rooms as audio-only, and to make the number of occupants after which a new occupant starts muted configurable (it was hardcoded now). Strictly speaking, this is unrelated to this issue, but it touches on the same subject. :)
