### ISSUE TITLE
Enable Screenshare for Firefox version > 51

### ISSUE THREAD

**Issue by lufik** [igniterealtime/ofmeet-openfire-plugin#24]
Hi,

   please enable desktop sharing by default for Firefox version > 51 like jitsi-meeting already has.

It's enough to change https://github.com/igniterealtime/ofmeet-openfire-plugin/blob/master/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/ConfigServlet.java line 163:
 config.put( "desktopSharingFirefoxMaxVersionExtRequired", -1 );
to:
 config.put( "desktopSharingFirefoxMaxVersionExtRequired", 51 );
or simply remove that line => don't overwrite the jitsi-meeting default from config.js.

I tested it with firefox 52 and desktop (application) sharing started working without any extension like it works for meet.jit.si.

Thanks,

Luf

**Comment by klou** [comment]
+1.  Does this work with ESR?/
