### ISSUE TITLE
 JVB does not seem to be working (session with more than 2 people)

### ISSUE THREAD

**Issue by ageekhere** [igniterealtime/ofmeet-openfire-plugin#30]
As of version 0.9.2 JVB does not seem to be working. When 2 people join audio and video work, when the 3rd person joins video goes black and audio cuts off. So only a session with 2 people in it work.

**Comment by guusdk** [comment]
I'm assuming that you're referring to OFMeet 0.9.2, not the JVB alone (which is available in another Github repository).

We're frequently using OFMeet to have conferences with many people at the same time. I'm assuming that the issue that you're experiencing is related to your local environment and/or network architecture.

In any case, this issue includes not enough details to meaningfully address a problem. I'm closing it for now.
