### ISSUE TITLE
ofmeet is out of step with Jitsi

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/ofmeet-openfire-plugin#35]
Openfire meetings is now out of step with Jitsi because of the following changes

1. Jicofo maven artifact upgraded to 1.1 which uses Smack 4.x
2. jitsi-videobridge-openfire is not up to date with jitsi-videobridge
3. Jitsi Meet has new UI changes (invite options) that break InterfaceConfigServlet

**Comment by guusdk** [comment]
I'm sorry, I missed this issue. I think all of this is addressed in #37 though :)

**Comment by deleolajide** [comment]
Yes please, they have all be addressed.
