### ISSUE TITLE
Update Jitsi-based dependencies to latest release.

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/ofmeet-openfire-plugin#37]

**Comment by guusdk** [comment]
Updated:
- Jitsi Jicofo from 1.0-20170809.150330-7 to 1.1-20171102.164223-6.
- Jitsi Meet from 1.0.2207 to 1.0.2419.
- Jitsi's Openfire plugin for Videobridge to version 2.2-20171103.213218-1 (which depends on Videobridge version 1.1-20171031.202356-10).

As a result, OFMeet now requires Java 8 to run. Note that Openfire does not (see https://github.com/igniterealtime/Openfire/pull/915)

Jitsi's upstream changes include a switch from Smack 3 to Smack 4. This can bring changes to runtime behavior.

I dropped the email listener (which provided FastPath support), as it's implementation was based on Smack 3.

**Comment by deleolajide** [comment]
> I dropped the email listener (which provided FastPath support), as it's implementation was based on Smack 3.

I have upgraded it from smack 3 to smack 4 and added it to the chatapi plugin instead.

**Comment by guusdk** [comment]
As none of these changes got released yet (they'll be in 0.9.3), I'll add the latest round of updates here:

- Jitsi Jicofo from 1.1-20171102.164223-6 to 1.1-20180103.054218-14.
- Jitsi Meet from 1.0.2419 to 1.0.2570.
- Jitsi's Openfire plugin for Videobridge to version 2.3-20180131.155320-1  (which depends on Videobridge version 1.1-20180130.233151-31).

**Comment by guusdk** [comment]
I've now updated Jicofo to 1.1-20180303.151352-15 to pull in a fix for #38.
