### ISSUE TITLE
Encoding hidden fields in ofmeet-conference-endpoint.jsp is causing an exception

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/ofmeet-openfire-plugin#40]
Not sure why, but I had to remove the encoding to get it to work

````
<form action="ofmeet-conference.jsp">
    <input type="hidden" name="confid" value="<%= confid %>">
    <input type="hidden" name="focus" value="<%= focus != null ? focus : "" %>">
    <center>
        <input type="submit" name="back" value="<fmt:message key="ofmeet.back" />">
    </center>
</form>
````

**Comment by guusdk** [comment]
I cannot reproduce this. Unless I can, I'm uncomfortable removing the URL-encoding, as that might inject nasty data. If anything, I think we should encoding everywhere. If you can reproduce the exception, I'd be interested to see how.

**Comment by deleolajide** [comment]
Lets go with the changes and re-open if re-appears again.
