### ISSUE TITLE
Force offocus to wait for ofmeet before attempting to connect to videobridge

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/ofmeet-openfire-plugin#42]
offocus does a service discovery at startup which sometimes happens before ofmeet is fully loaded and ready. I had to add a Thread.sleep(5000) hack to get consistent results.

**Comment by guusdk** [comment]
Thanks for taking care of this. I was annoyed by that stacktrace on
startup. That service discovery gets redone later, right - I don't think
we're actually missing data? As for the wait: I'm pretty sure that there's
a event that we can listen for. That will be a more consistent solution
than waiting for an arbitrary number of seconds.

**Comment by deleolajide** [comment]
Not sure if service discovery is tried again, but the list of videobridges remains empty causing offocus to assume there is no available VB. It became more pronounced with my custom version of XMPPTCPConnection with an openfire vitrualconnection.

**Comment by deleolajide** [comment]
There was a reference to this in the [open_chat ](https://igniterealtime.org/support/group_chat.jsp) at igniterealtime.org. Just to point out that I have only applied to my [clone](https://github.com/Traderlynk/ofmeet-openfire-plugin). I considered it a hack and not a fix.
