### ISSUE TITLE
Websocket support with Openfire 4.2.1+

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/ofmeet-openfire-plugin#49]
There is a check in ConfigServlet to provide a WS connection if the websocket plugin is available. Otherwise a BOSH connection is provided. OF 4.2.1 has websockets built-in and this test now fails.

**Comment by guusdk** [comment]
Are you sure about 4.2.1? https://issues.igniterealtime.org/browse/OF-1339 fix version is 4.2.0.
