### ISSUE TITLE
Group OF Meetings with other client in admin console

### ISSUE THREAD

**Issue by guusdk** [igniterealtime/ofmeet-openfire-plugin#55]
Various plugins that provide web clients are ordered under the Web Clients tab in the admin console. Meeting has its own tab, which has just one sub-tab, also called Meetings. We can organize things logically by moving that sub-tab to the Web Clients tab.

**Comment by deleolajide** [comment]
In my line of work, openfire meetings is more than just jitsi-meet webclient. It is an eco-system.

This what my webclients tab looks like:

![image](https://user-images.githubusercontent.com/110731/35857149-2a17aa94-0b30-11e8-9ab5-e364b6d49a44.png)

This what my meetings tab looks like 

![image](https://user-images.githubusercontent.com/110731/35857234-66300d32-0b30-11e8-8f97-ae3feeebb455.png)

Where should I put audio-conferencing with freeswitch ?

![image](https://user-images.githubusercontent.com/110731/35857300-9f9ad188-0b30-11e8-8e50-3603f7e9feca.png)

**Comment by guusdk** [comment]
Ah, only now I remember that we've discussed this before. We'll leave it as-is. I might forget about this, and come up with a brilliant idea to organize everything under "Webclient" - upon which I kindly request you to point me at this comment. :)
