### ISSUE TITLE
Top domain direct access - removing path /ofmeet/jitsi-meet in URL

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/ofmeet-openfire-plugin#7]
On current version of ofmeet  we access it via URL like "https://host.example.com/ofmeet/jitsi" 
we would expect a way to use it via top level domain https://host.example.com
Is there a way we can achieve this ? a config setting ?
Is there a way to set room URL as on previous version i.e r=room instead of /room

Thx for help and efforts

**Comment by guusdk** [comment]
This is currenlty not possible using OFMeet alone. Possibly, you can work with reverse proxies, but I've never tried that myself.
